//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 验收单
    /// </summary>
    public partial class Acceptance
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string BatchNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime Date { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public decimal Count { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public decimal UnitPrice { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public decimal AmountMoney { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Procedure { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public decimal UnqualifiedCount { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string WorksheetId { get; set; }
    	/// <summary>
        /// 1加工单验收2委外加工单验收
        /// </summary>
    	[DisplayName( "1加工单验收2委外加工单验收" )]
        public short Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string WarehouseId { get; set; }
    	/// <summary>
        /// 入库状态0未入库1已入库
        /// </summary>
    	[DisplayName( "入库状态0未入库1已入库" )]
        public short Storage { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string CheckEmployeeId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string ExamineEmployeeId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime ExamineDate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string StockRecordId { get; set; }
    
        public virtual Worksheet Worksheet { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Employee CheckEmployee { get; set; }
        public virtual Employee ExamineEmployee { get; set; }
        public virtual StockRecord StockRecord { get; set; }
    }
}
