//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 附件
    /// </summary>
    public partial class Attachment
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 文件名称
        /// </summary>
    	[DisplayName( "文件名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 文件类型
        /// </summary>
    	[DisplayName( "文件类型" )]
        public string FileType { get; set; }
    	/// <summary>
        /// 大小
        /// </summary>
    	[DisplayName( "大小" )]
        public decimal Size { get; set; }
    	/// <summary>
        /// 相对路径
        /// </summary>
    	[DisplayName( "相对路径" )]
        public string Url { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 搜索值
        /// </summary>
    	[DisplayName( "搜索值" )]
        public string SearchKey { get; set; }
    	/// <summary>
        /// 所属用户ID
        /// </summary>
    	[DisplayName( "所属用户ID" )]
        public string UserId { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
    	[DisplayName( "用户名" )]
        public string UserName { get; set; }
    	/// <summary>
        /// 下载次数
        /// </summary>
    	[DisplayName( "下载次数" )]
        public short DownloadCount { get; set; }
    	/// <summary>
        /// 最后访问时间
        /// </summary>
    	[DisplayName( "最后访问时间" )]
        public System.DateTime LastTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Summary { get; set; }
    }
}
