//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Company
    /// </summary>
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.StockRecord = new HashSet<StockRecord>();
            this.Order = new HashSet<Order>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 客户名称
        /// </summary>
    	[DisplayName( "客户名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 客户编号
        /// </summary>
    	[DisplayName( "客户编号" )]
        public string Code { get; set; }
    	/// <summary>
        /// 联系人
        /// </summary>
    	[DisplayName( "联系人" )]
        public string Contacts { get; set; }
    	/// <summary>
        /// 联系电话
        /// </summary>
    	[DisplayName( "联系电话" )]
        public string ContactNumber { get; set; }
    	/// <summary>
        /// 公司电话
        /// </summary>
    	[DisplayName( "公司电话" )]
        public string Tel { get; set; }
    	/// <summary>
        /// 邮箱
        /// </summary>
    	[DisplayName( "邮箱" )]
        public string Email { get; set; }
    	/// <summary>
        /// 地址
        /// </summary>
    	[DisplayName( "地址" )]
        public string Address { get; set; }
    	/// <summary>
        /// 传真
        /// </summary>
    	[DisplayName( "传真" )]
        public string Fax { get; set; }
    	/// <summary>
        /// 网站
        /// </summary>
    	[DisplayName( "网站" )]
        public string Website { get; set; }
    	/// <summary>
        /// 预存款
        /// </summary>
    	[DisplayName( "预存款" )]
        public decimal PreDeposit { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string LevelId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string SourceId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string IndustryId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string SalesmanId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string StatusId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string TypeId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string PropertyId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string StageId { get; set; }
    
        public virtual CompanyType Level { get; set; }
        public virtual CompanyType Source { get; set; }
        public virtual CompanyType Industry { get; set; }
        public virtual Employee Salesman { get; set; }
        public virtual CompanyType Status { get; set; }
        public virtual CompanyType Type { get; set; }
        public virtual CompanyType Property { get; set; }
        public virtual CompanyType Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRecord> StockRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
