//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModelContainer : DbContext
    {
        public DbModelContainer()
            : base("name=DbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<UserProperty> UserProperty { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<ProductMix> ProductMix { get; set; }
        public virtual DbSet<MixMaterial> MixMaterial { get; set; }
        public virtual DbSet<Procedure> Procedure { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ProcedureList> ProcedureList { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockRecord> StockRecord { get; set; }
        public virtual DbSet<RecordMaterial> RecordMaterial { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderMaterial> OrderMaterial { get; set; }
        public virtual DbSet<CapitalAccount> CapitalAccount { get; set; }
        public virtual DbSet<Allocation> Allocation { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetail { get; set; }
        public virtual DbSet<StockBack> StockBack { get; set; }
        public virtual DbSet<ProductionQuotation> ProductionQuotation { get; set; }
        public virtual DbSet<OfferDetail> OfferDetail { get; set; }
        public virtual DbSet<ProductionPlan> ProductionPlan { get; set; }
        public virtual DbSet<Worksheet> Worksheet { get; set; }
        public virtual DbSet<WorkingProcedure> WorkingProcedure { get; set; }
        public virtual DbSet<WorkingMaterial> WorkingMaterial { get; set; }
        public virtual DbSet<MaterialRequisition> MaterialRequisition { get; set; }
        public virtual DbSet<Acceptance> Acceptance { get; set; }
        public virtual DbSet<PlanStorage> PlanStorage { get; set; }
        public virtual DbSet<SystemParams> SystemParams { get; set; }
    }
}
