//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModelContainer : DbContext
    {
        public DbModelContainer()
            : base("name=DbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<UserProperty> UserProperty { get; set; }
        public virtual DbSet<DepartmentProperty> DepartmentProperty { get; set; }
        public virtual DbSet<RoleProperty> RoleProperty { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<MaterialForm> MaterialForm { get; set; }
        public virtual DbSet<ProductForm> ProductForm { get; set; }
        public virtual DbSet<PurchaseForm> PurchaseForm { get; set; }
        public virtual DbSet<MaterialRequisition> MaterialRequisition { get; set; }
        public virtual DbSet<ProductionPlan> ProductionPlan { get; set; }
    }
}
