//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 用户
    /// </summary>
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.StockRecord = new HashSet<StockRecord>();
            this.Order = new HashSet<Order>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 工号
        /// </summary>
    	[DisplayName( "工号" )]
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Name { get; set; }
    	/// <summary>
        /// 手机号
        /// </summary>
    	[DisplayName( "手机号" )]
        public string Phone { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 邮箱
        /// </summary>
    	[DisplayName( "邮箱" )]
        public string Email { get; set; }
    	/// <summary>
        /// 用户类型
        /// </summary>
    	[DisplayName( "用户类型" )]
        public short Type { get; set; }
    	/// <summary>
        /// 用户状态
        /// </summary>
    	[DisplayName( "用户状态" )]
        public short Status { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string PINCodes { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string DepartmentId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string RoleId { get; set; }
    	/// <summary>
        /// 籍贯
        /// </summary>
    	[DisplayName( "籍贯" )]
        public string NativePlace { get; set; }
    	/// <summary>
        /// 家庭地址
        /// </summary>
    	[DisplayName( "家庭地址" )]
        public string HomeAddress { get; set; }
    	/// <summary>
        /// 家庭电话
        /// </summary>
    	[DisplayName( "家庭电话" )]
        public string HomeTel { get; set; }
    	/// <summary>
        /// 住址
        /// </summary>
    	[DisplayName( "住址" )]
        public string Address { get; set; }
    	/// <summary>
        /// 出生日期
        /// </summary>
    	[DisplayName( "出生日期" )]
        public System.DateTime BirthDate { get; set; }
    	/// <summary>
        /// 性别
        /// </summary>
    	[DisplayName( "性别" )]
        public short Sex { get; set; }
    	/// <summary>
        /// 入职日期
        /// </summary>
    	[DisplayName( "入职日期" )]
        public System.DateTime EntryDate { get; set; }
    	/// <summary>
        /// 试用天数
        /// </summary>
    	[DisplayName( "试用天数" )]
        public short TrialDays { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 离职日期
        /// </summary>
    	[DisplayName( "离职日期" )]
        public System.DateTime QuitDate { get; set; }
    	/// <summary>
        /// 民族
        /// </summary>
    	[DisplayName( "民族" )]
        public string Nation { get; set; }
    	/// <summary>
        /// 婚姻状态
        /// </summary>
    	[DisplayName( "婚姻状态" )]
        public string MarriageStatus { get; set; }
    	/// <summary>
        /// 政治状态
        /// </summary>
    	[DisplayName( "政治状态" )]
        public string PoliticalStatus { get; set; }
    	/// <summary>
        /// 毕业学校
        /// </summary>
    	[DisplayName( "毕业学校" )]
        public string GraduateSchool { get; set; }
    	/// <summary>
        /// 专业
        /// </summary>
    	[DisplayName( "专业" )]
        public string Major { get; set; }
    	/// <summary>
        /// 合同到期日
        /// </summary>
    	[DisplayName( "合同到期日" )]
        public System.DateTime ContractEndDate { get; set; }
    	/// <summary>
        /// 工资银行卡号
        /// </summary>
    	[DisplayName( "工资银行卡号" )]
        public string BankAccount { get; set; }
    	/// <summary>
        /// 医疗保险号
        /// </summary>
    	[DisplayName( "医疗保险号" )]
        public string MedicalInsuranceAccount { get; set; }
    	/// <summary>
        /// 养老保险号
        /// </summary>
    	[DisplayName( "养老保险号" )]
        public string PensionInsuranceAccount { get; set; }
    	/// <summary>
        /// 其他信息
        /// </summary>
    	[DisplayName( "其他信息" )]
        public string OtherInformation { get; set; }
    	/// <summary>
        /// 学历
        /// </summary>
    	[DisplayName( "学历" )]
        public string Education { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRecord> StockRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
