//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 领料单
    /// </summary>
    public partial class MaterialRequisition
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 领退料时间
        /// </summary>
    	[DisplayName( "领退料时间" )]
        public System.DateTime PickingTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 1领料2退料
        /// </summary>
    	[DisplayName( "1领料2退料" )]
        public short Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string WorksheetId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string StockRecordId { get; set; }
    
        public virtual Worksheet Worksheet { get; set; }
        public virtual StockRecord StockRecord { get; set; }
    }
}
