//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// MixMaterial
    /// </summary>
    public partial class MixMaterial
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 产品名称
        /// </summary>
    	[DisplayName( "产品名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 规格
        /// </summary>
    	[DisplayName( "规格" )]
        public string Specifications { get; set; }
    	/// <summary>
        /// 数量
        /// </summary>
    	[DisplayName( "数量" )]
        public decimal Count { get; set; }
    	/// <summary>
        /// 单价
        /// </summary>
    	[DisplayName( "单价" )]
        public decimal UnitPrice { get; set; }
    	/// <summary>
        /// 损耗
        /// </summary>
    	[DisplayName( "损耗" )]
        public decimal Loss { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 来源
        /// </summary>
    	[DisplayName( "来源" )]
        public short Source { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string ProductMixId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string UnitId { get; set; }
    	/// <summary>
        /// 总价
        /// </summary>
    	[DisplayName( "总价" )]
        public decimal TotalPrice { get; set; }
    	/// <summary>
        /// 产品备注
        /// </summary>
    	[DisplayName( "产品备注" )]
        public string MaterialRemarks { get; set; }
    	/// <summary>
        /// 编号
        /// </summary>
    	[DisplayName( "编号" )]
        public string Code { get; set; }
    
        public virtual ProductMix ProductMix { get; set; }
        public virtual Material Material { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
