//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// OfferDetail
    /// </summary>
    public partial class OfferDetail
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 类型（1工序2原料）
        /// </summary>
    	[DisplayName( "类型（1工序2原料）" )]
        public short Type { get; set; }
    	/// <summary>
        /// 名称
        /// </summary>
    	[DisplayName( "名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 说明
        /// </summary>
    	[DisplayName( "说明" )]
        public string Summary { get; set; }
    	/// <summary>
        /// 单位价格
        /// </summary>
    	[DisplayName( "单位价格" )]
        public decimal UnitPrice { get; set; }
    	/// <summary>
        /// 单位数量
        /// </summary>
    	[DisplayName( "单位数量" )]
        public decimal UnitCount { get; set; }
    	/// <summary>
        /// 单位总价
        /// </summary>
    	[DisplayName( "单位总价" )]
        public decimal UnitAmount { get; set; }
    	/// <summary>
        /// 总计成本
        /// </summary>
    	[DisplayName( "总计成本" )]
        public decimal Amount { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string ProductionQuotationId { get; set; }
    
        public virtual ProductionQuotation ProductionQuotation { get; set; }
    }
}
