//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 订单
    /// </summary>
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.StockRecord = new HashSet<StockRecord>();
            this.OrderMaterial = new HashSet<OrderMaterial>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 订单号
        /// </summary>
    	[DisplayName( "订单号" )]
        public string Code { get; set; }
    	/// <summary>
        /// 创建日期
        /// </summary>
    	[DisplayName( "创建日期" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 订单日期
        /// </summary>
    	[DisplayName( "订单日期" )]
        public System.DateTime OrderDate { get; set; }
    	/// <summary>
        /// 送货日期
        /// </summary>
    	[DisplayName( "送货日期" )]
        public System.DateTime CompletionDate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string CompanyId { get; set; }
    	/// <summary>
        /// 单价级别
        /// </summary>
    	[DisplayName( "单价级别" )]
        public short PriceLevel { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string EmployeeId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string WarehouseId { get; set; }
    	/// <summary>
        /// 总金额
        /// </summary>
    	[DisplayName( "总金额" )]
        public decimal AmountMoney { get; set; }
    	/// <summary>
        /// 计划结账日期
        /// </summary>
    	[DisplayName( "计划结账日期" )]
        public System.DateTime StatementDate { get; set; }
    	/// <summary>
        /// 收货地址
        /// </summary>
    	[DisplayName( "收货地址" )]
        public string DeliveryAddress { get; set; }
    	/// <summary>
        /// 客户单号
        /// </summary>
    	[DisplayName( "客户单号" )]
        public string CustomerCode { get; set; }
    	/// <summary>
        /// 出入库状态
        /// </summary>
    	[DisplayName( "出入库状态" )]
        public short OutInStatus { get; set; }
    	/// <summary>
        /// 出账状态
        /// </summary>
    	[DisplayName( "出账状态" )]
        public short AccountStatus { get; set; }
    	/// <summary>
        /// 发票编号
        /// </summary>
    	[DisplayName( "发票编号" )]
        public string InvoiceCode { get; set; }
    	/// <summary>
        /// 资金账户ID
        /// </summary>
    	[DisplayName( "资金账户ID" )]
        public string CapitalAccountId { get; set; }
    	/// <summary>
        /// 订单类型(1销售订单2采购订单)
        /// </summary>
    	[DisplayName( "订单类型(1销售订单2采购订单)" )]
        public short Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRecord> StockRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMaterial> OrderMaterial { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual CapitalAccount CapitalAccount { get; set; }
    }
}
