//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 工序
    /// </summary>
    public partial class Procedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedure()
        {
            this.ProcedureList = new HashSet<ProcedureList>();
            this.WorkingProcedure = new HashSet<WorkingProcedure>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 工序名称
        /// </summary>
    	[DisplayName( "工序名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 工序编号
        /// </summary>
    	[DisplayName( "工序编号" )]
        public string StepCode { get; set; }
    	/// <summary>
        /// 工序单价
        /// </summary>
    	[DisplayName( "工序单价" )]
        public decimal Price { get; set; }
    	/// <summary>
        /// 工序内容
        /// </summary>
    	[DisplayName( "工序内容" )]
        public string Content { get; set; }
    	/// <summary>
        /// 修改时间
        /// </summary>
    	[DisplayName( "修改时间" )]
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 修改人
        /// </summary>
    	[DisplayName( "修改人" )]
        public string UpdateUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureList> ProcedureList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingProcedure> WorkingProcedure { get; set; }
    }
}
