//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 生产计划
    /// </summary>
    public partial class ProductionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionPlan()
        {
            this.Worksheet = new HashSet<Worksheet>();
            this.PlanStorage = new HashSet<PlanStorage>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public decimal Count { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string BatchNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public System.DateTime PlanDate { get; set; }
    	/// <summary>
        /// 计划状态
        /// </summary>
    	[DisplayName( "计划状态" )]
        public short Status { get; set; }
    	/// <summary>
        /// 预计完成日期
        /// </summary>
    	[DisplayName( "预计完成日期" )]
        public System.DateTime PlanCompleteDate { get; set; }
    	/// <summary>
        /// 完成日期
        /// </summary>
    	[DisplayName( "完成日期" )]
        public System.DateTime CompleteDate { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string OrderId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string ProductionQuotationId { get; set; }
    	/// <summary>
        /// 计划类型（1成品2半成品）
        /// </summary>
    	[DisplayName( "计划类型（1成品2半成品）" )]
        public short Type { get; set; }
    	/// <summary>
        /// 父级计划ID
        /// </summary>
    	[DisplayName( "父级计划ID" )]
        public string ParentId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
        public virtual ProductionQuotation ProductionQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worksheet> Worksheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanStorage> PlanStorage { get; set; }
    }
}
