//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 收付款账单
    /// </summary>
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptDetail = new HashSet<ReceiptDetail>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 账单编号
        /// </summary>
    	[DisplayName( "账单编号" )]
        public string Code { get; set; }
    	/// <summary>
        /// 账单类型（1收款2付款）
        /// </summary>
    	[DisplayName( "账单类型（1收款2付款）" )]
        public string Type { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 收付款日期
        /// </summary>
    	[DisplayName( "收付款日期" )]
        public System.DateTime BillDate { get; set; }
    	/// <summary>
        /// 总金额
        /// </summary>
    	[DisplayName( "总金额" )]
        public decimal AmountMoney { get; set; }
    	/// <summary>
        /// 实收金额
        /// </summary>
    	[DisplayName( "实收金额" )]
        public decimal NetReceipts { get; set; }
    	/// <summary>
        /// 抹0金额
        /// </summary>
    	[DisplayName( "抹0金额" )]
        public int IntegerMoney { get; set; }
    	/// <summary>
        /// 票据编号
        /// </summary>
    	[DisplayName( "票据编号" )]
        public string BillCode { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 应收金额
        /// </summary>
    	[DisplayName( "应收金额" )]
        public decimal ReceivableMoney { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string CompanyId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetail { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
