//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 系统日志
    /// </summary>
    public partial class SystemLog
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 日志级别
        /// </summary>
    	[DisplayName( "日志级别" )]
        public string Level { get; set; }
    	/// <summary>
        /// 方法位置
        /// </summary>
    	[DisplayName( "方法位置" )]
        public string Method { get; set; }
    	/// <summary>
        /// 日志内容
        /// </summary>
    	[DisplayName( "日志内容" )]
        public string Content { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    }
}
