//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 用户
    /// </summary>
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserProperty = new HashSet<UserProperty>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 登陆用户名
        /// </summary>
    	[DisplayName( "登陆用户名" )]
        public string LoginName { get; set; }
    	/// <summary>
        /// 密码
        /// </summary>
    	[DisplayName( "密码" )]
        public string Password { get; set; }
    	/// <summary>
        /// 姓名
        /// </summary>
    	[DisplayName( "姓名" )]
        public string Name { get; set; }
    	/// <summary>
        /// 工号
        /// </summary>
    	[DisplayName( "工号" )]
        public string JobNumber { get; set; }
    	/// <summary>
        /// 手机号
        /// </summary>
    	[DisplayName( "手机号" )]
        public string Phone { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 最后登陆时间
        /// </summary>
    	[DisplayName( "最后登陆时间" )]
        public string LoginTime { get; set; }
    	/// <summary>
        /// 邮箱
        /// </summary>
    	[DisplayName( "邮箱" )]
        public string Email { get; set; }
    	/// <summary>
        /// 用户类型
        /// </summary>
    	[DisplayName( "用户类型" )]
        public short Type { get; set; }
    	/// <summary>
        /// 用户状态
        /// </summary>
    	[DisplayName( "用户状态" )]
        public short Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProperty> UserProperty { get; set; }
    }
}
