//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 用户日志
    /// </summary>
    public partial class UserLog
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 日志类型
        /// </summary>
    	[DisplayName( "日志类型" )]
        public string Type { get; set; }
    	/// <summary>
        /// 日志内容
        /// </summary>
    	[DisplayName( "日志内容" )]
        public string Content { get; set; }
    	/// <summary>
        /// 用户ID
        /// </summary>
    	[DisplayName( "用户ID" )]
        public string UserId { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
    	[DisplayName( "用户名" )]
        public string UserName { get; set; }
    	/// <summary>
        /// 记录时间
        /// </summary>
    	[DisplayName( "记录时间" )]
        public System.DateTime CreateTime { get; set; }
    }
}
